version: '3'
services:
  screeps:
    image: screepers/screeps-launcher
    volumes:
      - ./config.yml:/screeps/config.yml
      - ./.steamKey:/screeps/.steamKey
      - screeps-data:/screeps
    ports:
      - 21025:21025/tcp
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    volumes:
      - redis-data:/data

  dev:
    image: node:12-buster
    working_dir: /code
    volumes:
      - .:/code
    entrypoint: npm run entrypoint


volumes:
  redis-data:
  mongo-data:
  screeps-data:
